# Containerfile
FROM ubi8/dotnet-90:9.0-2 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM ubi8/dotnet-90-runtime:9.0-2
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "demo-informator.dll"]
